/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_jni_TestJni */

#ifndef _Included_org_jni_TestJni
#define _Included_org_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jni_TestJni
 * Method:    xxx
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jni_TestJni_xxx
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
